/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['index.js']) {
  _$jscoverage['index.js'] = [];
  _$jscoverage['index.js'][1] = 0;
  _$jscoverage['index.js'][2] = 0;
  _$jscoverage['index.js'][3] = 0;
  _$jscoverage['index.js'][4] = 0;
}
_$jscoverage['index.js'][1]++;
exports.Validator = require("./validator").Validator;
_$jscoverage['index.js'][2]++;
exports.Filter = require("./filter").Filter;
_$jscoverage['index.js'][3]++;
exports.check = exports.Validator.check;
_$jscoverage['index.js'][4]++;
exports.sanitize = exports.Filter.sanitize;
_$jscoverage['index.js'].source = ["exports.Validator = require('./validator').Validator;","exports.Filter = require('./filter').Filter;","exports.check = exports.Validator.check;","exports.sanitize = exports.Filter.sanitize;"];
