const assert = require('assert');
const fs = require('fs');
const path = require('path');
const rewritePattern = require('regexpu-core');

const root = path.join(__dirname, '..');
const unicodeVersion = '18.0.0';

assert.strictEqual(require('regexpu-core/package.json').version, '6.5.2');
assert.strictEqual(require('regenerate-unicode-properties/package.json').version, '10.3.0');
assert.strictEqual(require('regenerate-unicode-properties/unicode-version'), unicodeVersion);
assert.strictEqual(
  require(require.resolve('regenerate-unicode-properties/unicode-version', {
    paths: [path.dirname(require.resolve('regexpu-core'))],
  })), unicodeVersion
);

const pattern = rewritePattern('\\p{RGI_Emoji}', 'v', {
  unicodeSetsFlag: 'transform',
  unicodeFlag: 'transform',
  unicodePropertyEscapes: 'transform',
});

const unicodeLicense = fs.readFileSync(
  path.join(root, 'test/fixtures/emoji-18.0/LICENSE.txt'), 'utf8'
).trim();
const toolLicense = fs.readFileSync(
  require.resolve('regenerate-unicode-properties/LICENSE-MIT.txt'), 'utf8'
).trim();
const license = `${unicodeLicense}\n\n${toolLicense}`
  .split('\n').map(line => (line ? ` * ${line}` : ' *')).join('\n');
const literal = JSON.stringify(pattern).slice(1, -1).replace(/'/g, "\\'");
const output = `/*!
${license}
 */

// Generated by npm run generate:emoji. Do not edit this pattern manually.
// Unicode Emoji 18.0 RGI_Emoji, including the Basic_Emoji components.
// https://www.unicode.org/Public/18.0.0/emoji/emoji-sequences.txt
// https://www.unicode.org/Public/18.0.0/emoji/emoji-zwj-sequences.txt
// regexpu-core 6.5.2; regenerate-unicode-properties 10.3.0.

export const emojiVersion = '18.0';

/* eslint-disable max-len */
export const emojiPattern = '${literal}';
/* eslint-enable max-len */
`;
const destination = path.join(root, 'src/lib/util/emoji.js');

if (process.argv.includes('--check')) {
  assert.strictEqual(fs.readFileSync(destination, 'utf8'), output,
    'Emoji data is out of date. Run npm run generate:emoji.');
  process.stdout.write('Unicode Emoji 18.0 pattern is up to date.\n');
} else {
  fs.writeFileSync(destination, output);
  process.stdout.write('Generated Unicode Emoji 18.0 pattern.\n');
}
