name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20, 18]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
      - name: Install dependencies
        run: pnpm install --shamefully-hoist
      - name: Run tests
        run: pnpm build
      - if: matrix.node-version == 20
        name: Send coverage info to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage/cobertura-coverage.xml
