name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build on Node.js 22
    steps:
      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            index.js
            lib/
            es/
            validator.js
            validator.min.js
          retention-days: 1
  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        node-version: [22, 20, 18, 16, 14, 12, 10, 8]
    name: Run tests on Node.js ${{ matrix.node-version }}
    steps:
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test:ci
      - if: matrix.node-version == 22
        name: Send coverage info to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
