name: NPM Publish
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - name: Setup Node.js 24
      uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
      with:
        node-version: 24
        registry-url: https://registry.npmjs.org/
    - name: Checkout Repository
      uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
    - name: Install Dependencies
      run: npm install --legacy-peer-deps
    - name: Run Tests
      run: npm test
    - name: Publish Package to NPM Registry
      run: npm publish
